version: "3"
services:
  client_dev:
    build:
      context: .
      target: client_dev
    container_name: client_container
    expose:
      - 8050
    ports:
      - "8050:8050"
    profiles:
      - client_dev
    volumes:
      - ./clientCode:/home/app/code
    networks:
      serv:
  client:
    build:
      context: .
      target: client
    container_name: client_container
    expose:
      - 8050
    ports:
      - "8050:8050"
    profiles:
      - client_prod
    networks:
      serv:
  server:
    build:
      context: .
      target: server
    container_name: server_container
    ports:
      - "5000:5000"
    links:
      - db
    profiles:
      - prod
    networks:
      serv:
  server_dev:
    build:
      context: .
      target: server
    container_name: server_container
    ports:
      - "5000:5000"
    links:
      - db
    volumes:
      - ./ServerCode:/home/app/code
    profiles:
      - dev
    networks:
      serv:
  db:
    build:
      context: .
      target: database
    container_name: database_container

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2b4djnm3ed2dms
      - POSTGRES_DB=postgres
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles:
      - db
    networks:
      serv:
volumes:
  pgdata:
networks:
  serv: